// <auto-generated />
using System;
using CoDi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoDi.Data.Migrations
{
    [DbContext(typeof(CoDiContext))]
    [Migration("20260127161111_changedDailySongStats")]
    partial class changedDailySongStats
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoDi.Data.Contracts.Entities.DailySongStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date")
                        .HasColumnName("day");

                    b.Property<TimeOnly>("FirstPlayedAt")
                        .HasColumnType("time without time zone")
                        .HasColumnName("first_played_at");

                    b.Property<int>("SongId")
                        .HasColumnType("integer")
                        .HasColumnName("song_id");

                    b.Property<TimeSpan>("TimePlayedSec")
                        .HasColumnType("interval")
                        .HasColumnName("time_played_sec");

                    b.HasKey("Id");

                    b.HasIndex("SongId");

                    b.ToTable("daily_song_stats", (string)null);
                });

            modelBuilder.Entity("CoDi.Data.Contracts.Entities.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("artist");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("Song", (string)null);
                });

            modelBuilder.Entity("CoDi.Data.Contracts.Entities.DailySongStats", b =>
                {
                    b.HasOne("CoDi.Data.Contracts.Entities.Song", "Song")
                        .WithMany("DailyStats")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Song");
                });

            modelBuilder.Entity("CoDi.Data.Contracts.Entities.Song", b =>
                {
                    b.Navigation("DailyStats");
                });
#pragma warning restore 612, 618
        }
    }
}
